# Generated by Django 4.0.4 on 2022-04-23 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CSUClass',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('section', models.IntegerField()),
                ('session', models.CharField(max_length=30)),
                ('begindate', models.DateField()),
                ('enddate', models.DateField()),
                ('timestart', models.TimeField()),
                ('timeend', models.TimeField()),
                ('location', models.CharField(max_length=30)),
                ('instructor', models.CharField(max_length=60)),
                ('classtype', models.CharField(max_length=5)),
                ('openstatus', models.BooleanField()),
                ('enrolled', models.IntegerField()),
                ('capacity', models.IntegerField()),
                ('credits', models.DecimalField(decimal_places=1, max_digits=2)),
                ('consent', models.CharField(max_length=80)),
                ('lastadddate', models.DateField()),
                ('lastdropdate', models.DateField()),
                ('lastwithdrawdate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='CSUTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagname', models.CharField(max_length=30)),
                ('tagabbr', models.CharField(blank=True, default=None, max_length=6, null=True)),
                ('classassoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.csuclass')),
            ],
        ),
        migrations.CreateModel(
            name='CSUClassDays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=10)),
                ('classassoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.csuclass')),
            ],
        ),
    ]
