# Generated by Django 4.0.4 on 2022-04-27 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='csuclass',
            name='desc',
            field=models.TextField(null=True),
        ),
    ]
