# Generated by Django 4.0.4 on 2022-04-27 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_csuclass_semester_csuclass_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csuclass',
            name='section',
            field=models.CharField(max_length=5),
        ),
    ]
