# Generated by Django 4.0.4 on 2022-04-27 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_csuclass_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csuclass',
            name='begindate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='csuclass',
            name='enddate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='csuclass',
            name='lastadddate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='csuclass',
            name='lastdropdate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='csuclass',
            name='lastwithdrawdate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='csuclass',
            name='timeend',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='csuclass',
            name='timestart',
            field=models.TimeField(null=True),
        ),
    ]
