# Generated by Django 4.0.4 on 2022-04-28 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_csuclass_cid_alter_csuclass_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='csuclass',
            name='specialtopic',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
